### ISSUE TITLE
Linker error in STRUCK code.. How to solve this

### ISSUE THREAD

**Issue by AneeshCEN** [gnebehay/STRUCK#1]
Error   6   error LNK2019: unresolved external symbol "public: void __thiscall ImageRep::Hist(class Rect<int> const &,class Eigen::Matrix<double,10000,1,2,10000,1> &)const " (?Hist@ImageRep@@QBEXABV?$Rect@H@@AAV?$Matrix@N$0CHBA@$00$01$0CHBA@$00@Eigen@@@Z) referenced in function "private: virtual void __thiscall HistogramFeatures::UpdateFeatureVector(class Sample const &)" (?UpdateFeatureVector@HistogramFeatures@@EAEXABVSample@@@Z)  C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   5   error LNK2019: unresolved external symbol "public: float __thiscall HaarFeature::Eval(class Sample const &)const " (?Eval@HaarFeature@@QBEMABVSample@@@Z) referenced in function "private: virtual void __thiscall HaarFeatures::UpdateFeatureVector(class Sample const &)" (?UpdateFeatureVector@HaarFeatures@@EAEXABVSample@@@Z)  C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   7   error LNK2019: unresolved external symbol "public: __thiscall ImageRep::ImageRep(class cv::Mat const &,bool,bool,bool)" (??0ImageRep@@QAE@ABVMat@cv@@_N11@Z) referenced in function "public: void __thiscall Tracker::Initialise(class cv::Mat const &,class Rect<float>)" (?Initialise@Tracker@@QAEXABVMat@cv@@V?$Rect@M@@@Z)  C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   4   error LNK2019: unresolved external symbol "public: __thiscall HaarFeature::HaarFeature(class Rect<float> const &,int)" (??0HaarFeature@@QAE@ABV?$Rect@M@@H@Z) referenced in function "private: void __thiscall HaarFeatures::GenerateSystematic(void)" (?GenerateSystematic@HaarFeatures@@AAEXXZ)   C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   3   error LNK2019: unresolved external symbol "public: __thiscall HaarFeature::~HaarFeature(void)" (??1HaarFeature@@QAE@XZ) referenced in function "private: void __thiscall HaarFeatures::GenerateSystematic(void)" (?GenerateSystematic@HaarFeatures@@AAEXXZ) C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   2   error LNK2019: unresolved external symbol "public: __thiscall Features::Features(void)" (??0Features@@QAE@XZ) referenced in function "public: __thiscall HaarFeatures::HaarFeatures(class Config const &)" (??0HaarFeatures@@QAE@ABVConfig@@@Z) C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   9   error LNK2019: unresolved external symbol "public: __thiscall Config::Config(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??0Config@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function _main C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   1   error LNK2019: unresolved external symbol "protected: void __thiscall Features::SetCount(int)" (?SetCount@Features@@IAEXH@Z) referenced in function "public: __thiscall HaarFeatures::HaarFeatures(class Config const &)" (??0HaarFeatures@@QAE@ABVConfig@@@Z)  C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK
Error   8   error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class Config const &)" (??6@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AAV01@ABVConfig@@@Z) referenced in function _main   C:\Users\anc6kor\Documents\Visual Studio 2010\Projects\STRUCK\STRUCK\STRUCK.obj STRUCK

**Comment by gnebehay** [comment]
What opencv version are you using?

**Comment by ruoanran** [comment]
Can I use opencv2.4.8?

**Comment by endeavorui** [comment]
I successfully installed STRUCK following the instruction. The executive file was created in the build folder. However, when I typed STRUCK in the terminal, it always inform me that STRUCK: command not found.

Any ideas about how to use it? I have eigen3 and opencv3.1 installed. No error in compiling.

**Comment by gnebehay** [comment]
Have you tried ./STRUCK ?

**Comment by endeavorui** [comment]
Thank you so much. Stupid me. It works perfectly.
